language: go

before_install:
  - go get github.com/mattn/goveralls

go:
  - "1.16.x"
  - "latest"

script:
  go test -v ./... -covermode=count -coverprofile=coverage.out $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $GOVERALLS_TOKEN