language: go

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

go:
  - "1.16.x"

script:
  - go test -v ./... -coverprofile=coverage.out
  - gover
  - travis_retry $GOPATH/bin/goveralls -coverprofile gover.coverprofile -service travis-ci
