language: go

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

go:
  - "1.16.x"

script:
  go test -v ./... -covermode=count -coverprofile=coverage.out $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $GOVERALLS_TOKEN